PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX crew: <http://www.crew-vre.net/ontology#>
SELECT $recuri $uri $ssrc $startTime $endTime $firstTimestamp $packetsSeen $packetsMissed $bytes $rtpType $cname $name $email $phoneNumber $location $tool $note $graph
WHERE {
    GRAPH $graph {
        $recuri rdf:type crew:Recording .
        $recuri crew:has-stream $uri .
        $uri crew:has-ssrc $ssrc .
        $uri crew:has-start-time $startTime .
        $uri crew:has-end-time $endTime .
        $uri crew:has-first-timestamp $firstTimestamp .
        $uri crew:has-packets-seen $packetsSeen .
        $uri crew:has-packets-missed $packetsMissed .
        $uri crew:has-bytes $bytes .
        $uri crew:has-rtp-type $rtpType .
        OPTIONAL { $uri crew:has-cname $cname } .
        OPTIONAL { $uri crew:has-name $name } .
        OPTIONAL { $uri crew:has-email $email } .
        OPTIONAL { $uri crew:has-phone-number $phoneNumber } .
        OPTIONAL { $uri crew:has-location $location } .
        OPTIONAL { $uri crew:has-tool $tool } .
        OPTIONAL { $uri crew:has-note $note }
    }
}
