PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX crew: <http://www.crew-vre.net/ontology#>
SELECT $uri $id $startTime $endTime $selectedVideoStream $selectedAudioStream
WHERE {
    GRAPH $graph {
        $uri rdf:type crew:Recording .
        $uri crew:has-id $id
        $uri crew:has-start-time $startTime
        $uri crew:has-end-time $endTime
        $uri crew:has-selected-video-stream $selectedVideoStream
        $uri crew:has-selected-audio-stream $selectedAudioStream
    }
}
