PREFIX pf:      <http://jena.hpl.hp.com/ARQ/property#>
PREFIX rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX dc:      <http://purl.org/dc/elements/1.1/>
PREFIX foaf:    <http://xmlns.com/foaf/0.1/>
PREFIX annotea: <http://www.w3.org/2000/10/annotation-ns#>
PREFIX crew:    <http://www.crew-vre.net/ontology#>

SELECT *
WHERE
{
	GRAPH ?graph
	{ 
		{
			?s rdf:type ?type .
			?s dc:title ?title .
			OPTIONAL { ?s dc:description ?desc }
			OPTIONAL { ?s crew:hasRecordingId ?recordingId }
		}
		UNION
		{
			?s rdf:type ?type .
			?s foaf:givenName ?given_name ; foaf:family_name ?family_name .
		}
	}
}