/**
 * Copyright (c) 2008-2009, University of Bristol
 * Copyright (c) 2008-2009, University of Manchester
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1) Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *
 * 2) Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * 3) Neither the names of the University of Bristol and the
 *    University of Manchester nor the names of their
 *    contributors may be used to endorse or promote products derived from this
 *    software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 */
package net.crew_vre.jena.vocabulary;

import com.hp.hpl.jena.rdf.model.Model;
import com.hp.hpl.jena.rdf.model.ModelFactory;
import com.hp.hpl.jena.rdf.model.Property;
import com.hp.hpl.jena.rdf.model.Resource;

/**
 * Vocabulary definitions from http://iugo.ilrt.bris.ac.uk/IugoPortal/data/ontology/iugo.rdf
 * @author Auto-generated by schemagen on 15 Jun 2007 14:02 (modified by Mike J)
 */
public class IUGO {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();

    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://www.ilrt.bristol.ac.uk/iugo#";

    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS
     *  @return the namespace of the vocabuary is a string
     */
    public static String getURI() {return NS;}

    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );

    public static final Property holdsRole = m_model.createProperty( "http://www.ilrt.bristol.ac.uk/iugo#holdsRole" );

    public static final Property visitingFellowAt = m_model.createProperty( "http://www.ilrt.bristol.ac.uk/iugo#visitingFellowAt" );

    public static final Property employedBy = m_model.createProperty( "http://www.ilrt.bristol.ac.uk/iugo#employedBy" );

    public static final Property affiliatedOrg = m_model.createProperty( "http://www.ilrt.bristol.ac.uk/iugo#affiliatedOrg" );

    public static final Property flickrHomepage = m_model.createProperty( "http://www.ilrt.bristol.ac.uk/iugo#flickrHomepage" );

    public static final Property hasLocation = m_model.createProperty( "http://www.ilrt.bristol.ac.uk/iugo#hasLocation" );

    public static final Property hasMainStartDate = m_model.createProperty( "http://www.ilrt.bristol.ac.uk/iugo#hasMainStartDate" );

    public static final Property hasSubject = m_model.createProperty( "http://www.ilrt.bristol.ac.uk/iugo#hasSubject" );

    public static final Property hasTag = m_model.createProperty( "http://www.ilrt.bristol.ac.uk/iugo#hasTag" );

    public static final Resource TutorialSession = m_model.createResource( "http://www.ilrt.bristol.ac.uk/iugo#TutorialSession" );

    public static final Resource EducationalOrg = m_model.createResource( "http://www.ilrt.bristol.ac.uk/iugo#EducationalOrg" );

    public static final Resource Company = m_model.createResource( "http://www.ilrt.bristol.ac.uk/iugo#Company" );

    public static final Resource Retrievable = m_model.createResource( "http://www.ilrt.bristol.ac.uk/iugo#Retrievable" );

    public static final Resource Event = m_model.createResource( "http://www.ilrt.bristol.ac.uk/iugo#Event" );

    public static final Resource Author = m_model.createResource( "http://www.ilrt.bristol.ac.uk/iugo#Author" );

    public static final Resource MainEvent = m_model.createResource( "http://www.ilrt.bristol.ac.uk/iugo#MainEvent" );

}
