PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX crew: <http://www.crew-vre.net/ontology#>
SELECT $uri $guid $name $description $type
WHERE {
    $bridgeRegistry crew:has-bridge $uri .
    $uri rdf:type crew:Bridge .
    $uri dc:identifier $guid .
    $uri dc:title $name .
    $uri dc:description $description .
    $uri dc:type $type
}
