PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX eswc: <http://www.eswc2006.org/technologies/ontology#>
SELECT $graph $roleId $roleName $eventId
WHERE {
    GRAPH $graph {
        $personId eswc:holdsRole $roleId .
        $roleId dc:title $roleName .
        $roleId eswc:isRoleAt $eventId
    }
}