PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX eswc: <http://www.eswc2006.org/technologies/ontology#>
PREFIX crew: <http://www.crew-vre.net/ontology#>
SELECT $graph $id $title $description $startDateTime $endDateTime $locationId $locationName
$proceedings $programme $recordingId
WHERE {
    GRAPH $graph {
        $id dc:title $title .
        OPTIONAL { $id eswc:hasStartDateTime $startDateTime .
                   $id eswc:hasEndDateTime $endDateTime } .
        OPTIONAL { $id dc:description $description } .
        OPTIONAL { $id eswc:hasProgramme $programme } .
        OPTIONAL { $id eswc:hasProceedings $proceedings }
    }
}
