# fragment - not a full sparql query. The MainEventDAO implementation class will construct the
# full query based on the parameters it receives.
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX eswc: <http://www.eswc2006.org/technologies/ontology#>
PREFIX iugo: <http://www.ilrt.bristol.ac.uk/iugo#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX crew: <http://www.crew-vre.net/ontology#>
SELECT $graph $id $title $description $startDateTime $endDateTime $startDate $endDate $skosLocationId $creationDate $skosLocationName
WHERE {
    GRAPH $graph {
        $id rdf:type iugo:MainEvent .
        $id dc:title $title .
        $id crew:hasStartDate $startDate .
        $id crew:hasEndDate $endDate .
        OPTIONAL {
            $id eswc:hasStartDateTime $startDateTime .
            $id eswc:hasEndDateTime $endDateTime .
        } .
        OPTIONAL { $id dc:description $description } .