/**
 * Copyright (c) 2008-2009, University of Bristol
 * Copyright (c) 2008-2009, University of Manchester
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1) Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *
 * 2) Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * 3) Neither the names of the University of Bristol and the
 *    University of Manchester nor the names of their
 *    contributors may be used to endorse or promote products derived from this
 *    software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 */
package net.crew_vre.jena.vocabulary;

import com.hp.hpl.jena.rdf.model.Model;
import com.hp.hpl.jena.rdf.model.ModelFactory;
import com.hp.hpl.jena.rdf.model.Property;
import com.hp.hpl.jena.rdf.model.Resource;

/**
 * Vocabulary definitions from http://iugo.ilrt.bris.ac.uk/IugoPortal/data/ontology/eswc2006.rdf
 * @author Auto-generated by schemagen on 15 Jun 2007 14:03 (modified by Mike J.)
 */
public class ESWC2006 {

    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();

    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://www.eswc2006.org/technologies/ontology#";

    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS
     *  @return the namespace of the vocabuary is a string
     */
    public static String getURI() {return NS;}

    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );

    public static final Property isRoleAt = m_model.createProperty( "http://www.eswc2006.org/technologies/ontology#isRoleAt" );

    public static final Property hasAttendee = m_model.createProperty( "http://www.eswc2006.org/technologies/ontology#hasAttendee" );

    public static final Property hasProgramme = m_model.createProperty( "http://www.eswc2006.org/technologies/ontology#hasProgramme" );

    public static final Property agreesWith = m_model.createProperty( "http://www.eswc2006.org/technologies/ontology#agreesWith" );

    public static final Property relatedToEvent = m_model.createProperty( "http://www.eswc2006.org/technologies/ontology#relatedToEvent" );

    public static final Property hasMenu = m_model.createProperty( "http://www.eswc2006.org/technologies/ontology#hasMenu" );

    public static final Property extends_ = m_model.createProperty( "http://www.eswc2006.org/technologies/ontology#extends" );

    public static final Property isProvidedBy = m_model.createProperty( "http://www.eswc2006.org/technologies/ontology#isProvidedBy" );

    public static final Property holdsRole = m_model.createProperty( "http://www.eswc2006.org/technologies/ontology#holdsRole" );

    public static final Property hasPart = m_model.createProperty( "http://www.eswc2006.org/technologies/ontology#hasPart" );

    public static final Property evidenceAgainst = m_model.createProperty( "http://www.eswc2006.org/technologies/ontology#evidenceAgainst" );

    public static final Property hasSponsorship = m_model.createProperty( "http://www.eswc2006.org/technologies/ontology#hasSponsorship" );

    public static final Property isPartOf = m_model.createProperty( "http://www.eswc2006.org/technologies/ontology#isPartOf" );

    public static final Property hasRole = m_model.createProperty( "http://www.eswc2006.org/technologies/ontology#hasRole" );

    public static final Property forEvent = m_model.createProperty( "http://www.eswc2006.org/technologies/ontology#forEvent" );

    public static final Property implements_ = m_model.createProperty( "http://www.eswc2006.org/technologies/ontology#implements" );

    public static final Property evidenceFor = m_model.createProperty( "http://www.eswc2006.org/technologies/ontology#evidenceFor" );

    public static final Property plansToAttend = m_model.createProperty( "http://www.eswc2006.org/technologies/ontology#plansToAttend" );

    public static final Property hasLocation = m_model.createProperty( "http://www.eswc2006.org/technologies/ontology#hasLocation" );

    public static final Property disagreesWith = m_model.createProperty( "http://www.eswc2006.org/technologies/ontology#disagreesWith" );

    public static final Property isProviderOf = m_model.createProperty( "http://www.eswc2006.org/technologies/ontology#isProviderOf" );

    public static final Property hasRelatedArtefact = m_model.createProperty( "http://www.eswc2006.org/technologies/ontology#hasRelatedArtefact" );

    public static final Property hasTopic = m_model.createProperty( "http://www.eswc2006.org/technologies/ontology#hasTopic" );

    public static final Property heldBy = m_model.createProperty( "http://www.eswc2006.org/technologies/ontology#heldBy" );

    public static final Property isLocationFor = m_model.createProperty( "http://www.eswc2006.org/technologies/ontology#isLocationFor" );

    public static final Property attendeeAt = m_model.createProperty( "http://www.eswc2006.org/technologies/ontology#attendeeAt" );

    public static final Property influencedBy = m_model.createProperty( "http://www.eswc2006.org/technologies/ontology#influencedBy" );

    public static final Property isTopicOf = m_model.createProperty( "http://www.eswc2006.org/technologies/ontology#isTopicOf" );

    public static final Property hasCall = m_model.createProperty( "http://www.eswc2006.org/technologies/ontology#hasCall" );

    public static final Property hasStartDateTime = m_model.createProperty( "http://www.eswc2006.org/technologies/ontology#hasStartDateTime" );

    public static final Property hasCostCurrency = m_model.createProperty( "http://www.eswc2006.org/technologies/ontology#hasCostCurrency" );

    public static final Property hasNotificationDeadline = m_model.createProperty( "http://www.eswc2006.org/technologies/ontology#hasNotificationDeadline" );

    public static final Property hasEndDateTime = m_model.createProperty( "http://www.eswc2006.org/technologies/ontology#hasEndDateTime" );

    public static final Property hasSubmissionInstructions = m_model.createProperty( "http://www.eswc2006.org/technologies/ontology#hasSubmissionInstructions" );

    public static final Property hasCameraReadyDeadline = m_model.createProperty( "http://www.eswc2006.org/technologies/ontology#hasCameraReadyDeadline" );

    public static final Property biblioReference = m_model.createProperty( "http://www.eswc2006.org/technologies/ontology#biblioReference" );

    public static final Property hasCostAmount = m_model.createProperty( "http://www.eswc2006.org/technologies/ontology#hasCostAmount" );

    public static final Property hasSubmissionDeadline = m_model.createProperty( "http://www.eswc2006.org/technologies/ontology#hasSubmissionDeadline" );

    public static final Resource CommunalPlace = m_model.createResource( "http://www.eswc2006.org/technologies/ontology#CommunalPlace" );

    public static final Resource IndustrialTrack = m_model.createResource( "http://www.eswc2006.org/technologies/ontology#IndustrialTrack" );

    public static final Resource Role = m_model.createResource( "http://www.eswc2006.org/technologies/ontology#Role" );

    public static final Resource Reviewer = m_model.createResource( "http://www.eswc2006.org/technologies/ontology#Reviewer" );

    public static final Resource IndustryChair = m_model.createResource( "http://www.eswc2006.org/technologies/ontology#IndustryChair" );

    public static final Resource AccommodationPlace = m_model.createResource( "http://www.eswc2006.org/technologies/ontology#AccommodationPlace" );

    public static final Resource TalkEvent = m_model.createResource( "http://www.eswc2006.org/technologies/ontology#TalkEvent" );

    public static final Resource LocalOrganiser = m_model.createResource( "http://www.eswc2006.org/technologies/ontology#LocalOrganiser" );

    public static final Resource PosterSession = m_model.createResource( "http://www.eswc2006.org/technologies/ontology#PosterSession" );

    public static final Resource Proceedings = m_model.createResource( "http://www.eswc2006.org/technologies/ontology#Proceedings" );

    public static final Resource SponsorshipChair = m_model.createResource( "http://www.eswc2006.org/technologies/ontology#SponsorshipChair" );

    public static final Resource EatingPlace = m_model.createResource( "http://www.eswc2006.org/technologies/ontology#EatingPlace" );

    public static final Resource BreakEvent = m_model.createResource( "http://www.eswc2006.org/technologies/ontology#BreakEvent" );

    public static final Resource Sponsorship = m_model.createResource( "http://www.eswc2006.org/technologies/ontology#Sponsorship" );

    public static final Resource MeetingRoomPlace = m_model.createResource( "http://www.eswc2006.org/technologies/ontology#MeetingRoomPlace" );

    public static final Resource AdditionalReviewer = m_model.createResource( "http://www.eswc2006.org/technologies/ontology#AdditionalReviewer" );

    public static final Resource TutorialsChair = m_model.createResource( "http://www.eswc2006.org/technologies/ontology#TutorialsChair" );

    public static final Resource Paper = m_model.createResource( "http://www.eswc2006.org/technologies/ontology#Paper" );

    public static final Resource AcademicEvent = m_model.createResource( "http://www.eswc2006.org/technologies/ontology#AcademicEvent" );

    public static final Resource CallForProposals = m_model.createResource( "http://www.eswc2006.org/technologies/ontology#CallForProposals" );

    public static final Resource CallForPapers = m_model.createResource( "http://www.eswc2006.org/technologies/ontology#CallForPapers" );

    public static final Resource Poster = m_model.createResource( "http://www.eswc2006.org/technologies/ontology#Poster" );

    public static final Resource TrackEvent = m_model.createResource( "http://www.eswc2006.org/technologies/ontology#TrackEvent" );

    public static final Resource PaperPresentation = m_model.createResource( "http://www.eswc2006.org/technologies/ontology#PaperPresentation" );

    public static final Resource CallForPosters = m_model.createResource( "http://www.eswc2006.org/technologies/ontology#CallForPosters" );

    public static final Resource MealBreak = m_model.createResource( "http://www.eswc2006.org/technologies/ontology#MealBreak" );

    public static final Resource ConferenceChair = m_model.createResource( "http://www.eswc2006.org/technologies/ontology#ConferenceChair" );

    public static final Resource SlideSet = m_model.createResource( "http://www.eswc2006.org/technologies/ontology#SlideSet" );

    public static final Resource OrganisingCommitteeMember = m_model.createResource( "http://www.eswc2006.org/technologies/ontology#OrganisingCommitteeMember" );

    public static final Resource WorkshopsChair = m_model.createResource( "http://www.eswc2006.org/technologies/ontology#WorkshopsChair" );

    public static final Resource Programme = m_model.createResource( "http://www.eswc2006.org/technologies/ontology#Programme" );

    public static final Resource TutorialEvent = m_model.createResource( "http://www.eswc2006.org/technologies/ontology#TutorialEvent" );

    public static final Resource SessionEvent = m_model.createResource( "http://www.eswc2006.org/technologies/ontology#SessionEvent" );

    public static final Resource WorkshopEvent = m_model.createResource( "http://www.eswc2006.org/technologies/ontology#WorkshopEvent" );

    public static final Resource CallForParticipation = m_model.createResource( "http://www.eswc2006.org/technologies/ontology#CallForParticipation" );

    public static final Resource ResearchTrack = m_model.createResource( "http://www.eswc2006.org/technologies/ontology#ResearchTrack" );

    public static final Resource Call = m_model.createResource( "http://www.eswc2006.org/technologies/ontology#Call" );

    public static final Resource Excursion = m_model.createResource( "http://www.eswc2006.org/technologies/ontology#Excursion" );

    public static final Resource Reception = m_model.createResource( "http://www.eswc2006.org/technologies/ontology#Reception" );

    public static final Resource ConferenceVenuePlace = m_model.createResource( "http://www.eswc2006.org/technologies/ontology#ConferenceVenuePlace" );

    public static final Resource KeynoteTalk = m_model.createResource( "http://www.eswc2006.org/technologies/ontology#KeynoteTalk" );

    public static final Resource MealEvent = m_model.createResource( "http://www.eswc2006.org/technologies/ontology#MealEvent" );

    public static final Resource Webmaster = m_model.createResource( "http://www.eswc2006.org/technologies/ontology#Webmaster" );

    public static final Resource DrinkingPlace = m_model.createResource( "http://www.eswc2006.org/technologies/ontology#DrinkingPlace" );

    public static final Resource SessionChair = m_model.createResource( "http://www.eswc2006.org/technologies/ontology#SessionChair" );

    public static final Resource OrganisedEvent = m_model.createResource( "http://www.eswc2006.org/technologies/ontology#OrganisedEvent" );

    public static final Resource DemoPresentation = m_model.createResource( "http://www.eswc2006.org/technologies/ontology#DemoPresentation" );

    public static final Resource ProgrammeChair = m_model.createResource( "http://www.eswc2006.org/technologies/ontology#ProgrammeChair" );

    public static final Resource FreeTimeBreak = m_model.createResource( "http://www.eswc2006.org/technologies/ontology#FreeTimeBreak" );

    public static final Resource Delegate = m_model.createResource( "http://www.eswc2006.org/technologies/ontology#Delegate" );

    public static final Resource ConferenceEvent = m_model.createResource( "http://www.eswc2006.org/technologies/ontology#ConferenceEvent" );

    public static final Resource Artefact = m_model.createResource( "http://www.eswc2006.org/technologies/ontology#Artefact" );

    public static final Resource CoffeeBreak = m_model.createResource( "http://www.eswc2006.org/technologies/ontology#CoffeeBreak" );

    public static final Resource PosterPresentation = m_model.createResource( "http://www.eswc2006.org/technologies/ontology#PosterPresentation" );

    public static final Resource PublicityChair = m_model.createResource( "http://www.eswc2006.org/technologies/ontology#PublicityChair" );

    public static final Resource Place = m_model.createResource( "http://www.eswc2006.org/technologies/ontology#Place" );

    /** <p>A role that is only relevant in relation to the topic of the conference e.g.
     *  Semantic Web Technologies Coordinator at a Semantic Web Conference.</p>
     */
    public static final Resource DogfoodTsar = m_model.createResource( "http://www.eswc2006.org/technologies/ontology#DogfoodTsar" );

    public static final Resource NonAcademicEvent = m_model.createResource( "http://www.eswc2006.org/technologies/ontology#NonAcademicEvent" );

    public static final Resource DemoSession = m_model.createResource( "http://www.eswc2006.org/technologies/ontology#DemoSession" );

    public static final Resource DemosChair = m_model.createResource( "http://www.eswc2006.org/technologies/ontology#DemosChair" );

    public static final Resource ConferenceDinner = m_model.createResource( "http://www.eswc2006.org/technologies/ontology#ConferenceDinner" );

    public static final Resource PostersChair = m_model.createResource( "http://www.eswc2006.org/technologies/ontology#PostersChair" );

    public static final Resource WelcomeTalk = m_model.createResource( "http://www.eswc2006.org/technologies/ontology#WelcomeTalk" );

    public static final Resource Administrator = m_model.createResource( "http://www.eswc2006.org/technologies/ontology#Administrator" );

    public static final Resource Presenter = m_model.createResource( "http://www.eswc2006.org/technologies/ontology#Presenter" );

    public static final Resource SubmissionsChair = m_model.createResource( "http://www.eswc2006.org/technologies/ontology#SubmissionsChair" );

    public static final Resource Tutor = m_model.createResource( "http://www.eswc2006.org/technologies/ontology#Tutor" );

    public static final Resource PaperSession = m_model.createResource( "http://www.eswc2006.org/technologies/ontology#PaperSession" );

    public static final Resource SocialEvent = m_model.createResource( "http://www.eswc2006.org/technologies/ontology#SocialEvent" );

    public static final Resource CallForDemos = m_model.createResource( "http://www.eswc2006.org/technologies/ontology#CallForDemos" );

    public static final Resource ProgrammeCommitteeMember = m_model.createResource( "http://www.eswc2006.org/technologies/ontology#ProgrammeCommitteeMember" );

    public static final Resource Event = m_model.createResource( "http://www.eswc2006.org/technologies/ontology#Event" );

}
