PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX eswc: <http://www.eswc2006.org/technologies/ontology#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
SELECT $graph $id $name $personId $title $givenName $family_name $name
WHERE {
    GRAPH $graph {
        $id dc:title $name .
        $id rdf:type eswc:Role .
        $id eswc:heldBy $personId .
        $personId rdf:type foaf:Person .
        OPTIONAL { $personId foaf:title $title } .
        OPTIONAL { $personId foaf:givenName $givenName } .
        OPTIONAL { $personId foaf:family_name $family_name } .
        OPTIONAL { $personId foaf:name $name } .
        $id eswc:isRoleAt $eventId .
    }
}