PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX crew: <http://www.crew-vre.net/ontology#>
SELECT $uri $name $description
WHERE {
    $venueServer crew:has-venue $uri .
    $uri rdf:type crew:Venue .
    $uri dc:title $name .
    $uri dc:description $description
}
