PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX crew: <http://www.crew-vre.net/ontology#>
SELECT $recuri $uri $time $name $graph
WHERE {
    GRAPH $graph {
        $recuri rdf:type crew:Recording .
        $recuri crew:has-layout $uri .
        $uri crew:has-timestamp $time .
        $uri crew:has-name $name
    }
}
