PREFIX eswc: <http://www.eswc2006.org/technologies/ontology#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT $graph $id $title $description $type
WHERE {
    GRAPH $graph {
        $id dc:title $title .
        OPTIONAL { $id dc:description $description } .
        $id rdf:type <http://www.eswc2006.org/technologies/ontology#Paper> .
        OPTIONAL { $id rdf:type $type .
                   FILTER ($type = <http://www.ilrt.bristol.ac.uk/iugo#Retrievable>) } .
        $id eswc:relatedToEvent $eventId .
    }
}