PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX iugo: <http://www.ilrt.bristol.ac.uk/iugo#>
PREFIX eswc: <http://www.eswc2006.org/technologies/ontology#>
SELECT $graph $id $title $givenName $family_name $name $homepage $workplaceHomepage $flickrHomepage
WHERE {
    GRAPH $graph {
        $id rdf:type foaf:Person .
        OPTIONAL { $id foaf:title $title } .
        OPTIONAL { $id foaf:givenName $givenName } .
        OPTIONAL { $id foaf:family_name $family_name } .
        OPTIONAL { $id foaf:name $name } .
        OPTIONAL { $id foaf:homepage $homepage} .
        OPTIONAL { $id foaf:workplaceHomepage $workplaceHomepage } .
        OPTIONAL { $id iugo:flickrHomepage $flickrHomepage } .
        $id eswc:holdsRole $roleId .
        $roleId eswc:isRoleAt $eventId .
    }
}
ORDER by $family_name