PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX crew: <http://www.crew-vre.net/ontology#>
PREFIX portal: <http://www.aktors.org/ontology/portal#>
PREFIX memetic: <http://www.memetic-vre.net/ontologies/memetic-20050106-1#>
SELECT $subEvent $startTime $endTime $screen
WHERE {
    GRAPH $graph {
        $recordingId portal:has-sub-event $subEvent .
        $subEvent rdf:type <http://www.memetic-vre.net/ontologies/memetic-20050106-1#Screen> .
        $subEvent memetic:has-media-start-time $startTime .
        $subEvent memetic:has-media-end-time $endTime .
        $subEvent memetic:has-screen-capture $screen .
    }
}
ORDER BY $startTime
