PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX crew: <http://www.crew-vre.net/ontology#>
PREFIX memetic: <http://www.memetic-vre.net/ontologies/memetic-20050106-1#>
SELECT $id $eventId $videoUrl $screenUrl $startTime $endTime
WHERE {
    GRAPH $graph {
        $id rdf:type crew:Recording .
        $id crew:isRecordingAt $eventId .
        $id crew:hasVideoFile $videoUrl .
        $id crew:hasScreenFile $screenUrl .
        $id memetic:has-media-start-time $startTime .
        $id memetic:has-media-end-time $endTime .
    }
}