PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
SELECT $id $title $rdfslabel
WHERE {
    OPTIONAL { $id dc:title $label } .
    OPTIONAL { $id rdfs:label $rdfslabel } .
}
ORDER BY $rdfslabel