PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX pos: <http://www.w3.org/2003/01/geo/wgs84_pos#>
SELECT $graph $id $name $latitude $longitude $altitude
WHERE {
    GRAPH $graph {
        $id dc:title $name .
        OPTIONAL { $id pos:lat $latitude .
                   $id pos:long $longitude } .
    }
}