PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX crew: <http://www.crew-vre.net/ontology#>
SELECT $layoutUri $uri $name $stream $graph
WHERE {
    GRAPH $graph {
        $layoutUri rdf:type crew:Layout .
        $layoutUri crew:has-layout-position $uri .
        $uri crew:has-name $name .
        $uri crew:has-stream $stream
    }
}
